typography_spectrum: 0.25818670471198857
color:
  brandStrength: 0.981730269966647
  lightness: 0.4820916005410254
  saturation: 0.2839400439988822
  rhythmicContrast: 0.4905522735789418
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.07111556176096201
author:
  name: rich rodgers
  email: richrodgers@mac.com
  url: rich.rodgers
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/66324139-41cc-42d1-9d8f-0d0ccfb75013.png
name: rich.rodgers
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4b9e7fc3-fa1b-4849-a088-ebbd25bee1e8.png
title: Onward & Upward
